### Ejercicio: Datos climáticos estación

Link de datos: https://drive.google.com/drive/folders/1QD_GVY_KDRu6CEtN3qUmybuatw0WjRYx?usp=sharing


Crea un nuevo DataFrame con datos de 1 estaciones SENAMHI de diferentes regiones del Perú (https://www.senamhi.gob.pe/site/descarga-datos/).

Considerar lo siguiente a partir de "tutorial-para-la-descarga-de-datos.pdf".

Los datos de las columnas corresponden a:
- Columna A: Año
- Columna B: Mes
- Columna C: Día
- Columna D: Precipitación acumulada
- Columna E: Temperatura máxima
- Columna F: Temperatura mínima

En las celdas donde aparece -99.9 significa que no hay información disponible para esa variable

Luego:
1. Parsear el nombres de la estación Chosica y leer el archivo.
1. Calcula el promedio mensual de precipitación
1. Calcula el promedio anual de precipitación
2. Identifica el día más lluvioso
4. Exporta los resultados formateados en CSV

In [5]:
# Tu código aquí – Ejercicio: Estación

# Leer los datos de las estaciones y crear un DataFrame combinado
import os
files = os.listdir('/content/drive/MyDrive/10MO CICLO/CIENCIA DE DATOS AMBIENTALES /SENAMHI')  # Lista los archivos en el directorio
files

['qc00155213_santa_eulalia.txt',
 'qc00155224_santiago_de_tuna.txt',
 'qc00151205_CANCHACALLA.txt',
 'qc00151209_chosica.txt',
 'qc00000543_ñaña.txt']

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
# Parsear el nombre del archivo para obtener el código y nombre de la estación
import re

# Buscamos el archivo de Chosica dentro de la lista
station = [f for f in files if 'chosica' in f.lower()][0]

match = re.search(r'(qc\d+)_(.+)\.txt', station)
codigo = match.group(1)
nombre = match.group(2)

print(f"Código: {codigo}, Nombre: {nombre}")

Código: qc00151209, Nombre: chosica

In [7]:
# Leer el archivo CSV de la estación seleccionada
import pandas as pd
station_df = pd.read_table(f'/content/drive/MyDrive/10MO CICLO/CIENCIA DE DATOS AMBIENTALES /SENAMHI/{station}', header=None, sep=r'\s+', na_values=['-999','-99.9']) # Sin encabezados
station_df.columns = ['Año', 'Mes', 'Dia', 'Pr','Tmax', 'Tmin']  # Asignar nombres de columnas
# Formatear las columnas
station_df['Año'] = station_df['Año'].astype(int)
station_df['Mes'] = station_df['Mes'].astype(int)
station_df['Dia'] = station_df['Dia'].astype(int)

station_df.head()

    Año  Mes  Dia   Pr  Tmax  Tmin
0  1989   12    1  0.0   NaN   NaN
1  1989   12    2  0.0   NaN   NaN
2  1989   12    3  0.0   NaN   NaN
3  1989   12    4  0.0   NaN   NaN
4  1989   12    5  0.0   NaN   NaN

In [9]:
# Precipitacion mensual
precipitacion_mensual = station_df.groupby('Mes')['Pr'].mean()

# Precipitacion total anual
precipitacion_anual = station_df.groupby('Año')['Pr'].mean()

# Dia mas lluvioso
dia_mas_lluvioso = station_df.loc[station_df['Pr'].idxmax()]


print(f"Precipitación mensual:\n{precipitacion_mensual}\n")
print(f"Precipitación anual:\n{precipitacion_anual}\n")
print(f"El día más lluvioso fue el {dia_mas_lluvioso['Año']:.0f}-{dia_mas_lluvioso['Mes']:.0f}-{dia_mas_lluvioso['Dia']:.0f} con {dia_mas_lluvioso['Pr']} mm de precipitación.")

Precipitación mensual:
Mes
1     0.178629
2     0.307066
3     0.154278
4     0.084370
5     0.006732
6     0.000158
7     0.000840
8     0.000561
9     0.003184
10    0.004342
11    0.012899
12    0.044600
Name: Pr, dtype: float64

Precipitación anual:
Año
1989    0.000000
1990    0.040548
1991    0.038356
1992    0.022552
1993    0.040000
1994    0.120548
1995    0.053699
1996    0.089617
1997    0.025000
1998    0.054790
1999    0.108493
2000    0.090164
2001    0.070411
2002    0.095890
2003    0.058904
2004    0.015027
2005    0.016164
2006    0.080274
2007    0.043014
2008    0.057104
2009    0.154925
2010    0.003014
2011    0.065205
2012    0.192836
2013    0.019452
2014    0.187097
Name: Pr, dtype: float64

El día más lluvioso fue el 2012-4-4 con 37.0 mm de precipitación.

In [10]:
# Exportar a CSV
resultados_export = pd.DataFrame({
    'Precipitacion_promedio_mensual': precipitacion_mensual
})
resultados_export.to_csv(f'precipitacion_mensual_{nombre}.csv')

precipitacion_anual.to_csv(f'precipitacion_anual_{nombre}.csv')

print("Archivos CSV exportados")

Archivos CSV exportados

### Ejercicio 2: Datos climáticos multiestación

Crea un nuevo DataFrame con datos de 5 estaciones SENAMHI de diferentes regiones del Perú (https://www.senamhi.gob.pe/site/descarga-datos/).

Luego:
1. Paresear el nombres de la estaciones y leer los archivo.
1. Unir las db (Fecha, Est1, Est2, ...)
1. Calcula el promedio mensual de precipitación por región
2. Identifica el mes más lluvioso en cada estación
4. Exporta el resultado formateado a CSV

In [11]:
# Tu código aquí – Ejercicio 2: Multiestación

# Parsear el nombre y código de cada estación de la carpeta
import re

estaciones_info = []
for f in files:
    match = re.search(r'(qc\d+)_(.+)\.txt', f)
    codigo = match.group(1)
    nombre = match.group(2)
    estaciones_info.append((f, codigo, nombre))

estaciones_info

[('qc00155213_santa_eulalia.txt', 'qc00155213', 'santa_eulalia'),
 ('qc00155224_santiago_de_tuna.txt', 'qc00155224', 'santiago_de_tuna'),
 ('qc00151205_CANCHACALLA.txt', 'qc00151205', 'CANCHACALLA'),
 ('qc00151209_chosica.txt', 'qc00151209', 'chosica'),
 ('qc00000543_ñaña.txt', 'qc00000543', 'ñaña')]

In [12]:
# Leer cada estación y armar un diccionario {nombre_estacion: serie de precipitacion}
precip_estaciones = {}

for f, codigo, nombre in estaciones_info:
    df = pd.read_table(f'/content/drive/MyDrive/10MO CICLO/CIENCIA DE DATOS AMBIENTALES /SENAMHI/{f}', header=None, sep=r'\s+', na_values=['-999','-99.9'])
    df.columns = ['Año', 'Mes', 'Dia', 'Pr', 'Tmax', 'Tmin']
    df['Fecha'] = pd.to_datetime(dict(year=df['Año'], month=df['Mes'], day=df['Dia']))
    precip_estaciones[nombre] = df.set_index('Fecha')['Pr']

precip_estaciones

{'santa_eulalia': Fecha
 1963-12-01    0.0
 1963-12-02    0.0
 1963-12-03    0.0
 1963-12-04    0.0
 1963-12-05    0.2
              ...
 2014-01-27    0.0
 2014-01-28    0.0
 2014-01-29    0.0
 2014-01-30    0.0
 2014-01-31    0.0
 Name: Pr, Length: 18325, dtype: float64,
 'santiago_de_tuna': Fecha
 1963-12-01    NaN
 1963-12-02    NaN
 1963-12-03    NaN
 1963-12-04    NaN
 1963-12-05    NaN
              ...
 2014-01-27    0.0
 2014-01-28    0.0
 2014-01-29    0.0
 2014-01-30    4.2
 2014-01-31    1.7
 Name: Pr, Length: 18325, dtype: float64,
 'CANCHACALLA': Fecha
 1987-12-01    0.0
 1987-12-02    8.0
 1987-12-03    0.0
 1987-12-04    0.0
 1987-12-05    0.0
              ...
 2014-01-27    0.0
 2014-01-28    0.2
 2014-01-29    0.0
 2014-01-30    4.5
 2014-01-31    0.0
 Name: Pr, Length: 9559, dtype: float64,
 'chosica': Fecha
 1989-12-01    0.0
 1989-12-02    0.0
 1989-12-03    0.0
 1989-12-04    0.0
 1989-12-05    0.0
              ...
 2014-01-27    0.0
 2014-01-28    0.0
 2014-01-29    0.0
 2014-01-30    0.0
 2014-01-31    0.0
 Name: Pr, Length: 8828, dtype: float64,
 'ñaña': Fecha
 1964-02-01    0.0
 1964-02-02    0.0
 1964-02-03    0.0
 1964-02-04    0.0
 1964-02-05    0.0
              ...
 2014-01-27    0.0
 2014-01-28    0.0
 2014-01-29    0.0
 2014-01-30    0.0
 2014-01-31    0.0
 Name: Pr, Length: 18263, dtype: float64}

In [13]:
# Unir estaciones en un solo DataFrame (Fecha, Est1, Est2, ...)
clima_df = pd.DataFrame(precip_estaciones)
clima_df.head()

            santa_eulalia  santiago_de_tuna  CANCHACALLA  chosica  ñaña
Fecha
1963-12-01            0.0               NaN          NaN      NaN     NaN
1963-12-02            0.0               NaN          NaN      NaN     NaN
1963-12-03            0.0               NaN          NaN      NaN     NaN
1963-12-04            0.0               NaN          NaN      NaN     NaN
1963-12-05            0.2               NaN          NaN      NaN     NaN

In [14]:
# Promedio mensual de precipitación por estación
promedio_mensual_estaciones = clima_df.groupby(clima_df.index.month).mean()
promedio_mensual_estaciones

       santa_eulalia  santiago_de_tuna  CANCHACALLA   chosica    ñaña
Fecha
1           0.319776          1.784516     1.849940  0.178629  0.026185
2           0.543553          3.439153     3.080680  0.307066  0.033954
3           0.525434          3.186570     2.781514  0.154278  0.020926
4           0.022222          0.567551     0.555641  0.084370  0.001027
5           0.006583          0.041677     0.021712  0.006732  0.000701
6           0.000142          0.000133     0.000000  0.000158  0.002687
7           0.000000          0.005097     0.000000  0.000840  0.001309
8           0.001317          0.002304     0.000000  0.000561  0.000726
9           0.010278          0.030284     0.022667  0.003184  0.000621
10          0.023051          0.110887     0.210081  0.004342  0.001466
11          0.013830          0.270136     0.272400  0.012899  0.001958
12          0.109941          0.962273     1.125682  0.044600  0.006381

In [15]:
# Mes más lluvioso x cada estación
mes_mas_lluvioso_estacion = promedio_mensual_estaciones.idxmax()

print(f"Mes más lluvioso por estación:\n{mes_mas_lluvioso_estacion}")

Mes más lluvioso por estación:
santa_eulalia       2
santiago_de_tuna    2
CANCHACALLA         2
chosica             2
ñaña              2
dtype: int32

In [16]:
# Exportar a CSV
promedio_mensual_estaciones.to_csv('promedio_mensual_estaciones.csv')

print("Archivo CSV exportado")

Archivo CSV exportado